version: "3.9"
services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

    volumes:
      - "./data/postgres:/var/lib/postgresql/data_test"
    ports:
      - 5432:5432

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: celery worker --app=worker.celery --loglevel=info
    volumes:
      - ./project:/usr/src/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine



