version: "3.9"
services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

    volumes:
      - "./data/postgres:/var/lib/postgresql/data_test"
    ports:
      - 5432:5432

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker


  worker:
    build: ./
    command: celery -A app.worker.celery worker --loglevel=DEBUG
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - broker

  broker:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5566:5672"
      #local port 5672 was in use

  redis:
    image: redis:6-alpine

  flower:
    build: ./
    command: flower --app=app.worker.celery --host 0.0.0.0 --port=5555 --broker=redis://redis:6379/0
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - 5556:5555
    depends_on:
      - redis
      - web
      - worker
