version: "3.9"
services:
    db:
        restart: always
        image: postgres:9.6
        environment:
            - POSTGRES_DB=fastapi
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password

        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - 5432:5432

