"""Added required tables

Revision ID: 22ca0188bd66
Revises: 79300fdb427e
Create Date: 2021-09-23 13:41:32.485964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ca0188bd66'
down_revision = '79300fdb427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'catalog', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog', type_='unique')
    # ### end Alembic commands ###
