"""Added required tables

Revision ID: 3290932e6971
Revises: b397698bd756
Create Date: 2021-09-23 11:13:53.184642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3290932e6971'
down_revision = 'b397698bd756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
