"""Added required tables

Revision ID: 629bfee8e673
Revises: b2aacd031502
Create Date: 2021-10-07 11:44:13.579598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629bfee8e673'
down_revision = 'b2aacd031502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
