"""Added required tables

Revision ID: 79300fdb427e
Revises: 3290932e6971
Create Date: 2021-09-23 13:26:32.221504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79300fdb427e'
down_revision = '3290932e6971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('car', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car', 'catalog', ['catalog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'catalog_id')
    op.drop_table('catalog')
    # ### end Alembic commands ###
