"""Added required tables

Revision ID: 964cdef65df4
Revises: 3e022df7f8eb
Create Date: 2021-09-29 12:15:44.182280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964cdef65df4'
down_revision = '3e022df7f8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
