"""Added required tables

Revision ID: b5edeb831802
Revises: 22ca0188bd66
Create Date: 2021-09-23 14:35:35.490599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5edeb831802'
down_revision = '22ca0188bd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('car_id_name', 'car', ['catalog_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_id_name', 'car', type_='unique')
    # ### end Alembic commands ###
